/* =========================================================
   DBMS NEXUS — ISOLATED EXAMINATION ARENA (15 QUESTIONS PER CH)
========================================================= */

const OFFICIAL_EXAM_DATABASE = {
    1: [
        { q: "Which level of data abstraction describes HOW a record is physically stored on disk blocks?", a: ["View Level", "Logical Level", "Physical Level", "Conceptual Level"], correct: 2 },
        { q: "Which engine module translates DML queries into an evaluation plan and picks the lowest-cost alternative?", a: ["Buffer Manager", "DML Compiler & Optimizer", "File Manager", "Data Dictionary"], correct: 1 },
        { q: "Physical Data Independence ensures that:", a: ["Logical schema changes do not alter physical disks", "Physical schema modifications do not alter the logical schema", "Security views cannot be altered", "All tables must have indices"], correct: 1 },
        { q: "Which is a primary duty of the Database Administrator (DBA)?", a: ["Writing UI forms", "Schema definition and access authorization", "Managing network cables", "Compiling host languages"], correct: 1 },
        { q: "Which data structure in the storage manager stores metadata about database schemas and constraints?", a: ["Indices", "Data Dictionary", "Statistical Log", "Buffer Pool"], correct: 1 },
        { q: "What type of DML requires users to specify what data is needed without specifying how to get it?", a: ["Procedural DML", "Declarative (Non-procedural) DML", "Host DML", "Embedded DML"], correct: 1 },
        { q: "Why is SQL termed NOT Turing machine equivalent?", a: ["It cannot perform basic arithmetic", "It cannot perform arbitrary general computations or network/display I/O", "It lacks tables", "It is case sensitive"], correct: 1 },
        { q: "In a 2-tier database architecture, where does the application code execute?", a: ["Directly at the client machine invoking DB calls", "Exclusively on the server", "Inside the data dictionary", "In the buffer manager"], correct: 0 },
        { q: "Which user class accesses the database exclusively through pre-written application interfaces?", a: ["DBA", "Sophisticated Analysts", "Application Programmers", "Naive Users"], correct: 3 },
        { q: "Deciding what relation schemas to create and how to decompose attributes among them is a:", a: ["Business Decision", "Computer Science Decision", "Hardware Decision", "Network Decision"], correct: 1 },
        { q: "Which component coordinates the interaction among concurrent transactions to prevent inconsistencies?", a: ["Buffer Manager", "Concurrency-Control Manager", "DDL Interpreter", "Compiler Linker"], correct: 1 },
        { q: "What is an instance of a database?", a: ["The structural design of the DB", "The actual content of the database at a particular point in time", "A variable type", "A disk index"], correct: 1 },
        { q: "In an uncontrolled file system, concurrent withdrawals causing mismatched balances is an example of:", a: ["Data isolation", "Concurrency anomaly", "Physical independence", "Atomicity success"], correct: 1 },
        { q: "Which storage manager module allocates physical block space on disk storage?", a: ["Buffer Manager", "File Manager", "Transaction Manager", "Authorization Manager"], correct: 1 },
        { q: "What does the Query Evaluation Engine execute?", a: ["Raw SQL strings", "Low-level instructions generated by the DML compiler", "Operating system threads", "UI form inputs"], correct: 1 }
    ],
    2: [
        { q: "Which relational operator selects tuples that satisfy a given predicate condition?", a: ["Π (Pi)", "σ (Sigma)", "⋈ (Join)", "ρ (Rename)"], correct: 1 },
        { q: "A Candidate Key is defined as:", a: ["Any foreign key", "A minimal superkey", "All columns combined", "A view relation"], correct: 1 },
        { q: "The relational Cartesian Product $R \\times S$ produces:", a: ["Only matching tuples", "All possible pairs of tuples from R and S", "Union of unique values", "Intersection of keys"], correct: 1 },
        { q: "Which operator keeps only specified columns and removes duplicate rows?", a: ["σ (Select)", "Π (Project)", "∪ (Union)", "ρ (Rename)"], correct: 1 },
        { q: "Can a Candidate Key contain null values in standard relational theory?", a: ["Never", "Yes, unless declared NOT NULL", "Only if numeric", "Only in foreign tables"], correct: 1 },
        { q: "Theta Join $r \\bowtie_\\theta s$ is mathematically defined as:", a: ["$\\sigma_\\theta(r \\times s)$", "$\\Pi_\\theta(r \\cup s)$", "$r - s$", "$\\rho(r \\cap s)$"], correct: 0 },
        { q: "What must be true for two relations to be Union compatible ($r \\cup s$)?", a: ["Must share table names", "Same arity (column count) and compatible attribute domains", "Must have primary keys", "Same row count"], correct: 1 },
        { q: "Which operator produces tuples present in relation $r$ but NOT in relation $s$?", a: ["$r \\cup s$", "$r \\cap s$", "$r - s$", "$r \\times s$"], correct: 2 },
        { q: "What does the Rename operator (ρ) perform?", a: ["Deletes a table", "Assigns a name to the result of a relational algebra expression", "Sorts tuples", "Removes nulls"], correct: 1 },
        { q: "In relational theory, what is the arity of a relation?", a: ["Number of tuples", "Number of attributes (columns)", "Number of foreign keys", "Disk page count"], correct: 1 },
        { q: "What does the atomic domain requirement specify?", a: ["Values must be encrypted", "Attribute values must be indivisible units", "Values must be integers", "Values must be shared"], correct: 1 },
        { q: "In a Schema Diagram, how are primary key attributes indicated?", a: ["Written in red", "Underlined", "Marked with NULL", "Placed in separate boxes"], correct: 1 },
        { q: "What is a Foreign Key constraint?", a: ["Value in referencing relation must appear in referenced relation's primary key", "A key with no null values", "A temporary key", "A view key"], correct: 0 },
        { q: "Is the physical ordering of tuples in a relation relevant?", a: ["Yes, ordered by key", "No, relations are unordered sets of tuples", "Yes, ordered by insertion time", "Only in B-trees"], correct: 1 },
        { q: "What does $_{\\text{dept\\_name}}\\mathcal{G}_{\\text{avg}(\\text{salary})}(\\text{instructor})$ compute?", a: ["Average salary across the whole university", "Average salary calculated per department", "Total sum of salaries", "Count of instructors per department"], correct: 1 }
    ],
    3: [
        { q: "What is the evaluated output of '5 + null' in SQL arithmetic?", a: ["5", "0", "null", "Error"], correct: 2 },
        { q: "Which clause filters aggregated group results after grouping?", a: ["WHERE", "HAVING", "ORDER BY", "CHECK"], correct: 1 },
        { q: "Which operator tests for non-empty subquery results ($r \\neq \\emptyset$)?", a: ["EXISTS", "UNIQUE", "IN", "SOME"], correct: 0 },
        { q: "The SQL pattern match 'LIKE \\'%dar%\\'' finds:", a: ["Strings starting with 'dar'", "Strings ending with 'dar'", "Strings containing 'dar' anywhere", "Exact 3-letter strings"], correct: 2 },
        { q: "What does <code>UNION ALL</code> do in SQL?", a: ["Eliminates all duplicates", "Retains all duplicate tuples across queries", "Sorts descending", "Deletes nulls"], correct: 1 },
        { q: "Which statement modifies existing records conditionally without order anomalies?", a: ["ALTER TABLE", "UPDATE ... SET ... CASE", "INSERT INTO", "DROP TUPLE"], correct: 1 },
        { q: "How does SQL test if an attribute contains no data?", a: ["= null", "IS NULL", "== NULL", "EMPTY()"], correct: 1 },
        { q: "What does <code>salary > ALL (subquery)</code> evaluate to?", a: ["Greater than at least one tuple", "Greater than every single tuple in the subquery", "Equal to max salary", "True if subquery is empty"], correct: 1 },
        { q: "Which clause creates query-scoped temporary relations?", a: ["VIEW", "WITH", "TEMP", "LET"], correct: 1 },
        { q: "What does <code>count(*)</code> return in an SQL aggregation?", a: ["Distinct IDs", "Total number of tuples in the relation", "Null count", "Total sum"], correct: 1 },
        { q: "What does <code>(unknown OR true)</code> evaluate to in 3-valued logic?", a: ["unknown", "false", "true", "null"], correct: 2 },
        { q: "What happens if a non-aggregate attribute in SELECT is not in GROUP BY?", a: ["SQL ignores it", "SQL raises a syntax error", "Takes first value", "Returns NULL"], correct: 1 },
        { q: "What is a Scalar Subquery?", a: ["A query returning multiple relations", "A subquery returning exactly one single atomic value", "A query with no WHERE", "A union query"], correct: 1 },
        { q: "Which DDL statement adds a new column to an existing table?", a: ["UPDATE TABLE", "ALTER TABLE r ADD A D", "INSERT COLUMN", "MODIFY TABLE"], correct: 1 },
        { q: "Which comparison operator tests set membership in a subquery?", a: ["EXISTS", "IN", "SOME", "ALL"], correct: 1 }
    ],
    4: [
        { q: "In a NATURAL LEFT OUTER JOIN, non-matching right tuples become:", a: ["Zeros", "Empty Strings", "null", "Dropped"], correct: 2 },
        { q: "Which command permanently writes all updates from an active transaction?", a: ["ROLLBACK WORK", "COMMIT WORK", "SAVEPOINT", "GRANT ALL"], correct: 1 },
        { q: "Which statement revokes SELECT authorization on student from user U1?", a: ["REVOKE select ON student FROM U1;", "DELETE select FROM student FOR U1;", "DROP PRIVILEGE select ON U1;", "ALTER USER U1 DROP select;"], correct: 0 },
        { q: "What does 'ON DELETE CASCADE' enforce on foreign keys?", a: ["Rejects deletion", "Deletes matching child rows automatically", "Sets foreign key to null", "Aborts transaction"], correct: 1 },
        { q: "How is a View defined in SQL?", a: ["<code>CREATE VIEW v AS &lt;query expression&gt;</code>", "<code>MAKE VIEW v</code>", "<code>SAVE VIEW v</code>", "<code>NEW TABLE VIEW v</code>"], correct: 0 },
        { q: "What is a Materialized View?", a: ["A view in memory", "A view whose result is physically stored on disk and updated when base tables change", "A view with no keys", "A view that cannot be dropped"], correct: 1 },
        { q: "Which transaction property ensures all updates complete or are completely rolled back?", a: ["Atomicity", "Consistency", "Isolation", "Durability"], correct: 0 },
        { q: "Which command assigns a created role to a database user?", a: ["ASSIGN role TO user", "GRANT role TO user", "SET role = user", "ALTER USER ADD role"], correct: 1 },
        { q: "What does the <code>USING (course_id)</code> join construct do?", a: ["Specifies exactly which common columns to equate", "Forces full outer join", "Drops indices", "Creates a view"], correct: 0 },
        { q: "What data type stores large uninterpreted binary data like photos or videos?", a: ["CLOB", "BLOB", "VARCHAR", "NUMERIC"], correct: 1 },
        { q: "What does <code>ROLLBACK WORK</code> perform?", a: ["Shuts down server", "Undoes all updates performed by the active transaction", "Deletes tables", "Revokes permissions"], correct: 1 },
        { q: "Can a view with GROUP BY and aggregate functions be updated directly in SQL?", a: ["Yes, always", "No, SQL restricts updates on complex aggregated views", "Only by DBA", "Only if numeric"], correct: 1 },
        { q: "What does the Full Outer Join preserve?", a: ["Only matched rows", "All tuples from both left and right relations, padding missing attributes with null", "Only left rows", "Only right rows"], correct: 1 },
        { q: "What is the function of <code>CREATE INDEX</code>?", a: ["Enforce keys only", "Allow efficient data lookup without scanning all records", "Encrypt tables", "Backup data"], correct: 1 },
        { q: "What does <code>GRANT SELECT ON dept TO Amit WITH GRANT OPTION;</code> allow?", a: ["Amit can query and also grant SELECT privilege on dept to other users", "Amit cannot query", "Amit is DBA", "Amit cannot revoke"], correct: 0 }
    ]
};

let currentExamState = {
    chapter: 1,
    index: 0,
    score: 0
};

window.renderQuiz = function(chId) {
    currentExamState.chapter = (typeof chId === 'number' && chId > 0) ? chId : 1;
    const container = document.getElementById("quizArena");
    if (!container) return;

    container.innerHTML = `
        <div class="feature-card" style="text-align: center; padding: 35px 25px;">
            <div style="font-size: 42px; margin-bottom: 10px;">⚡</div>
            <h3 style="font-family: var(--font-tech); font-size: 22px; color: var(--secondary); margin-bottom: 8px;">
                OFFICIAL EXAMINATION PROTOCOL
            </h3>
            <p style="color: var(--muted); font-size: 13.5px; max-width: 600px; margin: 0 auto 20px;">
                Click below to launch the isolated examination arena. Scrolling is locked to evaluate direct recall.
            </p>
            <button onclick="launchIsolatedExam(${currentExamState.chapter})" class="primary-button" style="margin: auto;">
                ⚡ LAUNCH SECURE EXAM ARENA
            </button>
        </div>
    `;
};

window.launchIsolatedExam = function(chId) {
    if (chId) currentExamState.chapter = chId;
    currentExamState.index = 0;
    currentExamState.score = 0;

    document.body.style.overflow = "hidden";

    let modal = document.getElementById("isolatedExamModal");
    if (!modal) {
        modal = document.createElement("div");
        modal.id = "isolatedExamModal";
        modal.className = "modal-overlay active";
        modal.style.position = "fixed";
        modal.style.inset = "0";
        modal.style.background = "rgba(2, 4, 12, 0.96)";
        modal.style.display = "flex";
        modal.style.alignItems = "center";
        modal.style.justifyContent = "center";
        modal.style.zIndex = "99999";
        document.body.appendChild(modal);
    } else {
        modal.className = "modal-overlay active";
        modal.style.display = "flex";
    }

    renderIsolatedQuestion();
};

function renderIsolatedQuestion() {
    const modal = document.getElementById("isolatedExamModal");
    if (!modal) return;

    const list = OFFICIAL_EXAM_DATABASE[currentExamState.chapter] || OFFICIAL_EXAM_DATABASE[1];
    const qData = list[currentExamState.index];
    const total = list.length;
    const pct = ((currentExamState.index) / total) * 100;

    modal.innerHTML = `
        <div class="isolated-modal-card card-slide-in" id="examModalCard">
            <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid rgba(0, 234, 255, 0.2); padding-bottom: 12px; margin-bottom: 16px;">
                <div>
                    <span style="font-family: var(--font-tech); font-size: 9px; color: var(--danger); letter-spacing: 2px;">🔒 SECURE EXAM ARENA</span>
                    <h3 style="font-family: var(--font-tech); font-size: 16px; color: #fff; margin-top: 4px;">CHAPTER 0${currentExamState.chapter} ASSESSMENT</h3>
                </div>
                <div style="font-family: var(--font-tech); font-size: 12px; color: var(--primary);">
                    QUESTION ${currentExamState.index + 1} / ${total}
                </div>
            </div>

            <div style="width: 100%; height: 5px; background: rgba(255,255,255,0.08); border-radius: 10px; margin-bottom: 20px; overflow: hidden;">
                <div style="width: ${pct}%; height: 100%; background: linear-gradient(90deg, var(--secondary), var(--primary)); transition: width 0.35s ease;"></div>
            </div>

            <p style="font-size: 16px; font-weight: 700; color: #f4f7ff; margin-bottom: 20px; line-height: 1.6;">
                Q${currentExamState.index + 1}: ${qData.q}
            </p>

            <div style="display: grid; gap: 10px;" id="examOptionsBox">
                ${qData.a.map((opt, i) => `
                    <button onclick="submitExamAnswer(${i}, ${qData.correct}, this, event)" class="secondary-button" style="text-align: left; justify-content: flex-start; width: 100%; font-size: 13px; padding: 14px 18px; border-radius: 10px; border: 1px solid var(--border);">
                        <span style="font-family: var(--font-tech); color: var(--primary); margin-right: 10px;">${String.fromCharCode(65 + i)})</span> ${opt}
                    </button>
                `).join("")}
            </div>
            <div id="examFeedbackBox" style="margin-top: 14px; min-height: 24px; font-size: 13px; font-weight: bold;"></div>
        </div>
    `;
}

window.submitExamAnswer = function(selected, correct, btn, evt) {
    const parent = document.getElementById("examOptionsBox");
    if (parent) parent.querySelectorAll("button").forEach(b => b.disabled = true);
    const fb = document.getElementById("examFeedbackBox");
    const card = document.getElementById("examModalCard");
    const list = OFFICIAL_EXAM_DATABASE[currentExamState.chapter] || OFFICIAL_EXAM_DATABASE[1];

    if (selected === correct) {
        btn.style.borderColor = "var(--success)";
        btn.style.background = "rgba(32, 255, 155, 0.2)";
        if (card) card.classList.add("card-burst-correct");
        currentExamState.score++;
        fb.innerHTML = `<span style="color: var(--success);">✓ CORRECT!</span>`;
        if (window.ProgressManager && typeof ProgressManager.addXP === 'function') ProgressManager.addXP(30);
    } else {
        btn.style.borderColor = "var(--danger)";
        btn.style.background = "rgba(255, 73, 108, 0.2)";
        if (card) card.classList.add("card-burst-wrong");
        fb.innerHTML = `<span style="color: var(--danger);">✗ INCORRECT (Correct: ${String.fromCharCode(65 + correct)})</span>`;
    }

    setTimeout(() => {
        if (card) card.className = "isolated-modal-card card-slide-out";
        setTimeout(() => {
            currentExamState.index++;
            if (currentExamState.index < list.length) {
                renderIsolatedQuestion();
            } else {
                renderExamFinalResults();
            }
        }, 300);
    }, 900);
};

function closeExamArena() {
    const modal = document.getElementById("isolatedExamModal");
    if (modal) {
        modal.classList.remove("active");
        modal.remove();
    }
    document.body.style.overflow = "auto";
    if (typeof renderQuiz === "function") {
        renderQuiz(currentExamState.chapter);
    }
}
window.closeExamArena = closeExamArena;

function renderExamFinalResults() {
    const modal = document.getElementById("isolatedExamModal");
    if (!modal) return;
    const list = OFFICIAL_EXAM_DATABASE[currentExamState.chapter] || OFFICIAL_EXAM_DATABASE[1];
    const total = list.length;
    const pct = Math.round((currentExamState.score / total) * 100);
    const passed = pct >= 70;

    document.body.style.overflow = "auto";

    if (passed && currentExamState.chapter > 0 && window.ProgressManager && typeof ProgressManager.setChapterScore === 'function') {
        ProgressManager.setChapterScore(currentExamState.chapter, 100);
    }

    modal.innerHTML = `
        <div class="isolated-modal-card card-slide-in" style="text-align: center; padding: 35px;">
            <div style="font-size: 48px; margin-bottom: 12px;">${passed ? '🏆' : '⚠️'}</div>
            <h3 style="font-family: var(--font-tech); font-size: 24px; color: ${passed ? 'var(--success)' : 'var(--danger)'}; margin-bottom: 8px;">
                ${passed ? 'MASTERY VERIFIED!' : 'ASSESSMENT INCOMPLETE'}
            </h3>
            <p style="color: #f4f7ff; font-size: 15px; margin-bottom: 6px;">
                Final Score: <strong>${currentExamState.score} / ${total} (${pct}%)</strong>
            </p>
            <p style="color: var(--muted); font-size: 13px; margin-bottom: 22px;">
                ${passed ? 'Curriculum completed! Direct recall verified.' : 'Minimum 70% required to complete assessment. Try again!'}
            </p>
            <div style="display: flex; gap: 12px; justify-content: center;">
                <button onclick="launchIsolatedExam(${currentExamState.chapter})" class="secondary-button">↻ RETAKE</button>
                <button onclick="closeExamArena()" class="primary-button">✓ CLOSE</button>
            </div>
        </div>
    `;
}